# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:			  Nodlim
tagline:          Programming Exercises with Solutions
description:      >
                  Language agnostic programming problems,
                  with answers in several programming languages.
url:              "kranzuft.github.com/nodlim/"
baseurl:          /

gems: [pygments]

# Date settings
timezone: Australia/Sydney

collections:
  htmlprac:
    booknum: 1
    topic: "Hypertext Markup Language"
    title: "Hypertext Markup Language (HTML)"
    output: true
