# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:			  Nodlim
tagline:          Programming Exercises with Solutions
description:      >
                  Language agnostic programming problems,
                  with answers in several programming languages.
url:              "{{ site.github.url }}"

gems: 
  - pygments
  - jekyll-minifier

# Date settings
timezone: Australia/Sydney

collections:
  html:
    booknum: 1 
    topic: "Hypertext Markup Language"
    title: "Hypertext Markup Language"
    output: true
  algo:
    booknum: 2
    topic: "Algorithms"
    title: "Core Algorithms"
    output: true 
